### PR TITLE
Rework to fix the autowatch function

### PR DESCRIPTION
**Pull request by skystarUK**
I originally made a separate branch for this as I changed a lot, but it will only allow me to pull request to the origin/master.
Maybe you can take a look anyway, see if you like the changes.

I wrote descriptions of the changes in the commit messages, I am using atom.project.observeBuffers now to watch for editing of files, the code is simplified so its easy enough to understand.  Only tested on Win7, but nothing that should cause a problem.

### CODE REVIEW

**Comment by rehrumesh** [comment]
Thanks for the great work @skystarUK 👍 
I will test this tomorrow and merge.

**Review by rehrumesh — APPROVED** [review]

**Comment by rehrumesh** [comment]
@skystarUK  This pr includes #10 right?

**Comment by rehrumesh** [comment]
@skystarUK did a minor apm publish with this update. Thanks for the great contribution. :1st_place_medal:

**Comment by skystarUK** [comment]
Yes, that commit appeared to include #10 commits as well, although it superseded them all.  I wasn't sure when I made the new pull request if it would have, I thought it would just add the ones not previously Pull requested.
I have now closed the #10 pull request.

**Pull request merged**
